# -*- coding: utf-8 -*-
"""Linear Regression Deployment on streamLit .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19X1VJGfFofHO5mMV-ohidfL3mrN_Jj8a
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
# -----------------------------------
# Page Configuration
# -----------------------------------
st.set_page_config(
    page_title="Life Insuarance Prediction",
    page_icon="🏠",
    layout="centered"
)

st.title("🏠 Life Insuarance Prediction")
st.write("Predict Life Insuarance using Logistic Regression")

# -----------------------------------
# Load Dataset
# -----------------------------------
df = pd.read_csv("insurance_data.csv")

st.subheader("Dataset")
st.dataframe(df)

# -----------------------------------
# Train Model
# -----------------------------------
X_train, X_test, y_train, y_test = train_test_split(df[['age']],df.bought_insurance,train_size=0.8)
X = df.drop("insuarance", axis=1)


y = df["insuarance"]

model = LogisticRegression()
model.fit(X, y)

# -----------------------------------
# User Input
# -----------------------------------
st.subheader("Enter age of person")

age = st.number_input(
    "Age (in Years)",
    min_value=10,
    max_value=65,
    value=18,
    step=1
)

# -----------------------------------
# Prediction
# -----------------------------------
if st.button("Predict insuarance  "):

    prediction = model.predict([[age]])

    st.success(f"Predicted insuarance: ₹ {prediction[0]:,.2f}")

# -----------------------------------
# Model Information
# -----------------------------------
st.subheader("Model Details")

st.write("Coefficient:", model.coef_[0])
st.write("Intercept:", model.intercept_)
