# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qNQ7967ZKxveqOBHiGt2ivEfGJERgCcL
"""

# ==========================================
# Life Insurance Prediction using Streamlit
# Logistic Regression
# ==========================================

# Import required libraries
import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

# ------------------------------------------
# Page Title
# ------------------------------------------
st.title("🏥 Life Insurance Prediction using Logistic Regression")

st.write("""
This application predicts whether a person will buy life insurance
based on their age using Logistic Regression.
""")

# ------------------------------------------
# Upload Dataset
# ------------------------------------------
uploaded_file = st.file_uploader(
    "Upload insurance_data.csv",
    type=["csv"]
)

# Check if file is uploaded
if uploaded_file is not None:

    # Read CSV file
    df = pd.read_csv(uploaded_file)

    # ------------------------------------------
    # Display Dataset
    # ------------------------------------------
    st.subheader("Dataset")
    st.dataframe(df)

    # ------------------------------------------
    # Scatter Plot
    # ------------------------------------------
    st.subheader("Age vs Bought Insurance")

    fig, ax = plt.subplots(figsize=(7,4))

    ax.scatter(
        df["age"],
        df["bought_insurance"],
        color="red",
        marker="+"
    )

    ax.set_xlabel("Age")
    ax.set_ylabel("Bought Insurance")
    ax.set_title("Insurance Purchase Distribution")

    st.pyplot(fig)

    # ------------------------------------------
    # Prepare Data
    # ------------------------------------------
    X = df[["age"]]
    y = df["bought_insurance"]

    # Split dataset into training and testing
    X_train, X_test, y_train, y_test = train_test_split(
        X,
        y,
        train_size=0.8,
        random_state=42
    )

    # ------------------------------------------
    # Train Logistic Regression Model
    # ------------------------------------------
    model = LogisticRegression()

    model.fit(X_train, y_train)

    # ------------------------------------------
    # Model Accuracy
    # ------------------------------------------
    accuracy = model.score(X_test, y_test)

    st.subheader("Model Accuracy")

    st.success(f"Accuracy = {accuracy:.2f}")

    # ------------------------------------------
    # Show Model Parameters
    # ------------------------------------------
    st.subheader("Model Parameters")

    st.write("Coefficient (m):")

    st.write(model.coef_)

    st.write("Intercept (b):")

    st.write(model.intercept_)

    # ------------------------------------------
    # Show Test Predictions
    # ------------------------------------------
    st.subheader("Prediction on Test Data")

    prediction = model.predict(X_test)

    probability = model.predict_proba(X_test)

    result = X_test.copy()

    result["Actual"] = y_test.values

    result["Predicted"] = prediction

    result["Probability(No)"] = probability[:,0]

    result["Probability(Yes)"] = probability[:,1]

    st.dataframe(result)

    # ------------------------------------------
    # User Input
    # ------------------------------------------
    st.subheader("Predict Insurance Purchase")

    age = st.slider(
        "Select Age",
        min_value=18,
        max_value=100,
        value=35
    )

    # Predict
    pred = model.predict([[age]])

    prob = model.predict_proba([[age]])

    st.write("### Prediction Probability")

    st.write(f"Will NOT Buy Insurance : {prob[0][0]*100:.2f}%")

    st.write(f"Will Buy Insurance : {prob[0][1]*100:.2f}%")

    # Final Prediction
    if pred[0] == 1:
        st.success("✅ Person is likely to BUY insurance.")
    else:
        st.error("❌ Person is NOT likely to buy insurance.")

else:
    st.info("Please upload insurance_data.csv to continue.")